eco/eco-routes

- contracts/Inbox.sol
- contracts/IntentSource.sol
- contracts/interfaces/IInbox.sol
- contracts/interfaces/IIntentSource.sol
- contracts/types/Intent.sol
- test/IntentSource.spec.ts
most of the audit fixes. comment references are in the jira ticket
fixes findings 1, 3, 5.5, 6.1, 8.6
> Ed 4503: IntentSource simple audit fixes

- contracts/IntentSource.sol
- contracts/Prover.sol
This ticket addresses feedback from the Cantina Audit.
> ED-4499: Address Feedback from Cantina Audit - Feedback Item 8

- contracts/Inbox.sol
- contracts/IntentSource.sol
> 11 safe erc20

- contracts/Inbox.sol
- test/Inbox.spec.ts
- removed drain
- refunds excess fees in calls sending to hyperlane mailbox
> 15_fees_drain

- contracts/Inbox.sol
- contracts/IntentSource.sol
- contracts/interfaces/IInbox.sol
- test/Inbox.spec.ts
- test/IntentSource.spec.ts
event emissions related tickets
to be merged after 15_fees_drain
> 16 23 event emissions

- contracts/Inbox.sol
- contracts/IntentSource.sol
6.3 CEI framework
6.4 .call for native transfers
> 6.3 CEI pattern, 6.4 .call native transfers

- contracts/Inbox.sol
- contracts/IntentSource.sol
- contracts/interfaces/IInbox.sol
- test/Inbox.spec.ts
- test/IntentSource.spec.ts
> 17 zero claimant

- contracts/Prover.sol
- test/Prover.spec.ts
> finality block delay as a constructor param

- README.md
- package.json
updating project urls for repo change
> updating to eco org

- contracts/Prover.sol
Apply changes recommended by Cantina and held in this [Pull Request](https://github.com/eco/eco-routes/pull/138)
The pull request uses a more consistent approach to a couple of edge cases around leading zeroes.
This was modified and tested under the [AUDIT-RLP-TESTS](https://github.com/eco/eco-routes/tree/AUDIT-RLP-TESTS) branch.
> CANTINA AUDIT #7 - RLP Changes

- .eslintignore
- contracts/libs/Semver.sol
- contracts/test/TestProver.sol
- package.json
- scripts/deploy/addresses.ts
- scripts/publish/abi-export.ts
- scripts/publish/create_package.ts
- scripts/publish/gitUtils.ts
- scripts/publish/prepack.sh
- scripts/publish/publish.ts
- scripts/viem_deploy/ProtocolDeploy.ts
- scripts/viem_deploy/ProtocolVersion.ts
- scripts/viem_deploy/assets/utils/helper.ts
- scripts/viem_deploy/assets/utils/index.ts
- scripts/viem_deploy/assets/utils/intent.ts
- scripts/viem_deploy/assets/utils/utils.ts
- scripts/viem_deploy/contracts/mainnet.ts
- scripts/viem_deploy/tests/protocol.version.spec.ts
- yarn.lock
updating scripts to deploy without a npm tag suffix
adding git hash short to solidity version tag
updating deploys to work with new paths
> Ed 4686 npm 

- contracts/libs/Semver.sol
- contracts/test/TestProver.sol
- package.json
- scripts/viem_deploy/assets/utils/intent.ts
- scripts/viem_deploy/assets/utils/utils.ts
- scripts/viem_deploy/chains.ts
Fixing some typings in the npm routs-ts repo scripts
> Fix types hash

- contracts/libs/Semver.sol
- contracts/test/TestProver.sol
- package.json
- scripts/deploy/addresses.ts
- scripts/utils.ts
- scripts/viem_deploy/ProtocolDeploy.ts
- scripts/viem_deploy/chains.ts
- scripts/viem_deploy/config.ts
- scripts/viem_deploy/contracts/mainnet.ts
- scripts/viem_deploy/contracts/sepolia.ts
- scripts/viem_deploy/tests/protocol.deploy.spec.ts
- test/IntentSource.spec.ts
- yarn.lock
fix create3 calls in different retrys and pre network deploys
> Create3 inbox

- contracts/IntentSource.sol
- contracts/README.md
- contracts/Vault.sol
- contracts/interfaces/IIntentSource.sol
Emitting `IntentPartiallyFunded` for `fund` and `publishAndFund` when `allowPartial` is enabled
> fix(IntentSource): emit IntentPartiallyFunded

- contracts/IntentSource.sol
- contracts/Vault.sol
Handles the edge case where funder hash high/infinite allowance but low balance and wants to fund partially.
> fix(IntentSource): check funders balance

- LICENSE
This updates the license from MIT to BSL
> license update 

- foundry.toml
- Update solc version to 0.8.27
- Replace 'optimize' with correct 'optimizer' setting
- Remove unnecessary evm_version and fs_permissions
Verify that the project builds correctly with updated config settings
> Fix foundry config settings

- .github/workflows/publish.yaml
> Add Unichain and Ink

- .gitmodules
- scripts/Deploy.s.sol
- scripts/deploySingletonFactory.sh
world chain and other that dont support he singleton factory are going to use createx instead
> fix: EIP-155  and world chain will use createx 

- contracts/prover/HyperProver.sol
- contracts/prover/LayerZeroProver.sol
- contracts/prover/MetaProver.sol
- scripts/semantic-release/assets/utils/intent.ts
- test/HyperProver.spec.ts
- test/LayerZeroProver.spec.ts
- test/MetaProver.spec.ts
- test/prover/HyperProver.t.sol
- test/prover/LayerZeroProver.t.sol
- test/prover/MetaProver.t.sol
Fix audit issue: https://cantina.xyz/code/9fd0c3da-dd38-409f-8a8a-9e34da467509/findings?order_by=severity&finding=11
> fix: provers custom data handling

- contracts/Executor.sol
- contracts/Inbox.sol
- contracts/interfaces/IExecutor.sol
- contracts/interfaces/IInbox.sol
- test/HyperProver.spec.ts
- test/Inbox.spec.ts
- test/core/Executor.t.sol
https://cantina.xyz/code/9fd0c3da-dd38-409f-8a8a-9e34da467509/findings?order_by=severity&severity=critical,high,medium&finding=1
> fix: fulfill with executor instead of inbox itself as the msg.sender

- contracts/ERC7683/OriginSettler.sol
- test/interfaces/OriginSettler.t.sol
https://cantina.xyz/code/9fd0c3da-dd38-409f-8a8a-9e34da467509/findings?order_by=severity&finding=2
> fix: domainSeparatorV4 infinite recursion

- contracts/prover/LayerZeroProver.sol
- contracts/prover/MessageBridgeProver.sol
- contracts/prover/MetaProver.sol
- test/prover/LayerZeroProver.t.sol
- test/prover/MetaProver.t.sol
https://cantina.xyz/code/9fd0c3da-dd38-409f-8a8a-9e34da467509/findings?order_by=severity&finding=42
> fix: inconsistent gas limit handling in provers

- contracts/interfaces/IMetalayerRouterExt.sol
- contracts/prover/MetaProver.sol
- contracts/test/TestMetaRouter.sol
- test/prover/MetaProver.t.sol
https://cantina.xyz/code/9fd0c3da-dd38-409f-8a8a-9e34da467509/findings?order_by=severity&finding=20
> fix: metaProver.fetchFee uses the 4-parameter version of quoteDispatch

- contracts/ERC7683/OriginSettler.sol
- contracts/IntentSource.sol
- contracts/interfaces/ERC7683/IOriginSettler.sol
- contracts/interfaces/IIntentSource.sol
- contracts/types/ERC7683.sol
- test/OriginSettler.spec.ts
- utils/EcoERC7683.ts
https://github.com/eco/eco-routes/pull/310 was accidentally closed for some reason.
> fix: fix multiple issues in OriginSettler

- contracts/types/ERC7683.sol
- test/OriginSettler.spec.ts
https://cantina.xyz/code/a6e138e7-bc07-4a75-868b-5f35f01c0941/findings?finding=3
> fix: struct order in ORDER_DATA_TYPEHASH

- contracts/ERC7683/OriginSettler.sol
- test/OriginSettler.spec.ts
https://cantina.xyz/code/a6e138e7-bc07-4a75-868b-5f35f01c0941/findings?finding=5
> fix: incorrect chain ID used for native token rewards in origin settlement
